{
  a = 4;
  b = 10;
  jer = blah + ted;
  {
    t = clone( vote );
  }
  big =
    p(
      [ 2.7, 3, 4 ],
      {}, [ [] ],
      ( 3, 4, [q] ),
      { a=>3, 4=>b, [v,v]=>[q] },
      a = b,
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) )
    );
  a = 4;
  b = 10;
  jer = blah + ted;
  {
    t = clone( vote );
  }
  big =
    p(
      [ 2.7, 3, 4 ],
      {}, [ [] ],
      ( 3, 4, [q] ),
      { a=>3, 4=>b, [v,v]=>[q] },
      a = b,
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) )
    );
  a = 4;
  b = 10;
  jer = blah + ted;
  {
    t = clone( vote );
  }
  big =
    p(
      [ 2.7, 3, 4 ],
      {}, [ [] ],
      ( 3, 4, [q] ),
      { a=>3, 4=>b, [v,v]=>[q] },
      a = b,
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) )
    );
  a = 4;
  b = 10;
  jer = blah + ted;
  {
    t = clone( vote );
  }
  big =
    p(
      [ 2.7, 3, 4 ],
      {}, [ [] ],
      ( 3, 4, [q] ),
      { a=>3, 4=>b, [v,v]=>[q] },
      a = b,
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) )
    );
  a = 4;
  b = 10;
  jer = blah + ted;
  {
    t = clone( vote );
  }
  big =
    p(
      [ 2.7, 3, 4 ],
      {}, [ [] ],
      ( 3, 4, [q] ),
      { a=>3, 4=>b, [v,v]=>[q] },
      a = b,
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) )
    );
  a = 4;
  b = 10;
  jer = blah + ted;
  {
    t = clone( vote );
  }
  big =
    p(
      [ 2.7, 3, 4 ],
      {}, [ [] ],
      ( 3, 4, [q] ),
      { a=>3, 4=>b, [v,v]=>[q] },
      a = b,
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) ),
      a( b(c), per(clone,vote), a*b+c*(d+e+f*|*g) )
    );
}
